FROM resin/rpi-raspbian:stretch

MAINTAINER "ChieftainY2k@gmail.com"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y mc joe multitail curl wget php7.0-cli php-zip composer telnet mosquitto-clients git


#ADD ./mqtt-listener.php /mqtt-listener.php

#RUN mkdir /code
#ADD ./code /code

# Add Startup scripts

ADD ./run.sh /run.sh
RUN chmod a+x /run.sh
CMD /run.sh


