FROM resin/rpi-raspbian:stretch

MAINTAINER "ChieftainY2k@gmail.com"

ENV DEBIAN_FRONTEND noninteractive

# Common stuff

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y mc joe multitail curl wget telnet libraspberrypi-bin

# Install mqtt client

RUN apt-get install -y mosquitto-clients

# Install scripts

ADD ./health-reporter.sh /health-reporter.sh
RUN chmod a+x /health-reporter.sh

ADD ./run.sh /run.sh
RUN chmod a+x /run.sh
CMD /run.sh




