FROM resin/rpi-raspbian:stretch

MAINTAINER "ChieftainY2k@gmail.com"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get -y upgrade && apt-get install -y \
    apt-utils git mc joe multitail wget curl telnet git nginx

COPY nginx.conf /etc/nginx/nginx.conf

ADD ./run.sh /run.sh
RUN chmod a+x /run.sh
CMD /run.sh

EXPOSE 80

