FROM resin/rpi-raspbian:stretch@sha256:e4938fd283abc60021efa24f8ebbde9d3b0135849dd1297093b06a18578963b4

MAINTAINER "ChieftainY2k@gmail.com"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get -y upgrade && apt-get install -y \
    mc joe multitail curl wget \
    telnet mosquitto-clients cron \
    git libmosquitto-dev mosquitto-dev libcurl3-openssl-dev \
    openalpr openalpr-daemon openalpr-utils libopenalpr-dev libraspberrypi0 \
    php7.0-cli php-zip composer telnet mosquitto-clients \
    php-pear php-dev netcat

RUN apt-get install -y make

# Enable mosquitto lib in PHP

RUN echo "" | pecl install Mosquitto-alpha
RUN echo "extension=mosquitto.so" > /etc/php/7.0/mods-available/mosquitto.ini
RUN echo "extension=mosquitto.so" > /etc/php/7.0/cli/conf.d/20-mosquitto.ini

# Configure cron

ADD ./crontab.txt /crontab.txt
RUN crontab /crontab.txt

# Add Startup scripts

ADD ./run.sh /run.sh
RUN chmod a+x /run.sh
CMD /run.sh

