FROM resin/rpi-raspbian:stretch

MAINTAINER "ChieftainY2k@gmail.com"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y mc joe multitail curl wget \
    telnet mosquitto-clients \
    git libmosquitto-dev mosquitto-dev libcurl3-openssl-dev \
    openalpr openalpr-daemon openalpr-utils libopenalpr-dev libraspberrypi0


# Add Startup scripts

ADD ./run.sh /run.sh
RUN chmod a+x /run.sh
CMD /run.sh



